# This script will fetch Google Street View images based on a given locations
# text file, generated by the fetchLocations.py file

# You will need your own Google API key to use this.
# The sample locations run from downtown Toronto (43.654520000000005,-79.38570000000001)
# to North York, Ontario (43.76059,-79.41509). Change the origin, destination,
# and optional waypoints in config.json to change the location.

import json
import os
import urllib.request
import googlemaps

__dirname = os.path.dirname(os.path.realpath(__file__))
data = []

locationsFile = ''
imgFolder = ''
apiKey = ''
origin = ''
destination = ''
stops = []

# Get user config
with open(__dirname + '/config.json') as f:
    configFile = json.load(f)
    locationsFile = __dirname + '/' + configFile["locationsFile"] # get path to locations.txt
    imgFolder = __dirname + '/' + configFile["streetImagesDir"] # directory to save photos in
    apiKey = configFile["apiKey"]
    origin = configFile["origin"]
    destination = configFile["destination"]
    stops = configFile["stops"]

gmaps = googlemaps.Client(key=apiKey)
coords = {
    "origin": origin,
    "destination": destination,
    "waypoints": stops
}

directions = gmaps.directions(origin=origin, destination=destination, waypoints=stops[0]["location"])

# Make the directory (and path to dir if necessary) of images if it doesn't already exist yet
if not os.path.exists(imgFolder):
    os.makedirs(imgFolder)

# Fetch and store location data (lng, lat, etc.) line-by-line
with open(locationsFile) as f:
    data = f.readlines()

# Fetch the images
for i in range(len(data)):
    imageData = (data[i]).strip().split(',')
    try:
        imageUrl = "https://maps.googleapis.com/maps/api/streetview?size=640x640&location=" + imageData[0] + "," + imageData[1] + "&heading=" + imageData[2] + "&pitch=20&key=" + apiKey
        urllib.request.urlretrieve(imageUrl, imgFolder + '/' + str(i) + '.jpg')
    except:
        print("Error: could not fetch image.")